version: '3'
services:
    app:
        build:
            context: ./docker-config
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: ingot
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        container_name: 'ingot_app'
        volumes:
            - '.:/var/www/html/IngotApp'
        networks:
            - app
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'yousef'
            MYSQL_DATABASE: 'ingot'
            MYSQL_USER: 'yousef'
            MYSQL_PASSWORD: 'yousef'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        container_name: 'ingot_database'
        volumes:
            - 'ingotmysql:/var/lib/mysql'
        networks:
            - app
networks:
    app:
        driver: bridge
volumes:
    ingotmysql:
        driver: local
