<?php

return [

    'DEFAULT_MAX_DEPOSIT' => env('DEFAULT_MAX_DEPOSIT',1000000),
    'DEFAULT_MIN_DEPOSIT' => env('DEFAULT_MIN_DEPOSIT',0),

    'DEFAULT_MAX_WITHDRAW' => env('DEFAULT_MAX_WITHDRAW',1000000),
    'DEFAULT_MIN_WITHDRAW' => env('DEFAULT_MIN_WITHDRAW',0),
];
